### ISSUE TITLE
Self-Host storage connection s3 returns Invalid credentials error.

### ISSUE THREAD

**Issue by lb-ovc** [supabase/storage#568]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We are in the process of setting up a production server to host Supabase. While everything is functioning as expected, we are encountering an issue with the storage connection. For storage, we are using Exoscale.

This setup worked perfectly fine in our development environment. For the production setup, I replicated the same configuration from the dev system, only updating the access key and secret. However, in Supabase Studio, we are receiving an “invalid signature” error related to the storage connection.

Any insights or suggestions to resolve this issue would be greatly appreciated.

```
  "error": {
    "raw": "{\"metadata\":{},\"code\":\"AccessDenied\",\"httpStatusCode\":403,\"userStatusCode\":400,\"originalError\":{\"name\":\"JsonWebTokenError\",\"message\":\"invalid signature\"},\"error\":\"Unauthorized\"}",
    "name": "Error",
    "message": "invalid signature",
    "stack": "Error: invalid signature\n    at Object.AccessDenied (/app/dist/storage/errors.js:86:34)\n    at /app/dist/auth/jwt.js:110:48\n    at /app/node_modules/jsonwebtoken/verify.js:171:14\n    at /app/dist/auth/jwt.js:82:9\n    at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)\n    at /app/dist/auth/jwt.js:108:32\n    at new Promise (<anonymous>)\n    at verifyJWT (/app/dist/auth/jwt.js:107:12)\n    at Object.<anonymous> (/app/dist/http/plugins/jwt.js:19:56)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "msg": "unable to get owner"
}
```

Here is our configuration:
![Screenshot 2024-10-10 at 20 31 38](https://github.com/user-attachments/assets/9d4b8aa0-e002-43a0-8d5d-c51e3fa24b5b)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

We followed the tutorial from activenode on youtube on how to self-host supabase.

## Expected behavior

Buckets are shown in the UI and can be used.

## Screenshots

![image](https://github.com/user-attachments/assets/f485d81a-2e2d-4d63-bf73-b990ca8b90a1)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by lb-ovc** [comment]
Okay so i was able to fix it. I regenerated the `JWT_SECRET`, `ANON_KEY` and `SERVICE_ROLE_KEY` and now it works. Dunno what the problem was with the first keys tho. 


It would be good if this was better described on the error codes page for storage..
